#!/usr/bin/env bash

set -euo pipefail

CARGO_ABOUT_VERSION="0.8.2"
OUTPUT_FILE="${1:-$(pwd)/assets/licenses.md}"
TEMPLATE_FILE="script/licenses/template.md.hbs"
TMP_OUTPUT_FILE="$(mktemp "${OUTPUT_FILE}.tmp.XXXXXX")"
trap 'rm -f "$TMP_OUTPUT_FILE"' EXIT

fail_on_stderr() {
    local tmpfile=$(mktemp)
    "$@" 2> >(tee "$tmpfile" >&2)
    local rc=$?
    [ -s "$tmpfile" ] && rc=1
    rm "$tmpfile"
    return $rc
}

echo -n "" >"$TMP_OUTPUT_FILE"

{
    echo -e "# ###### THEME LICENSES ######\n"
    cat assets/themes/LICENSES

    echo -e "\n# ###### ICON LICENSES ######\n"
    cat assets/icons/LICENSES

    echo -e "\n# ###### CODE LICENSES ######\n"
} >>"$TMP_OUTPUT_FILE"

if ! cargo about --version | grep "cargo-about $CARGO_ABOUT_VERSION" &>/dev/null; then
    echo "Installing cargo-about@$CARGO_ABOUT_VERSION..."
    cargo install "cargo-about@$CARGO_ABOUT_VERSION"
else
    echo "cargo-about@$CARGO_ABOUT_VERSION is already installed."
fi

echo "Generating cargo licenses"
if [ -z "${ALLOW_MISSING_LICENSES-}" ]; then FAIL_FLAG=--fail; else FAIL_FLAG=""; fi
if [ -z "${ALLOW_MISSING_LICENSES-}" ]; then WRAPPER=fail_on_stderr; else WRAPPER=""; fi
set -x
$WRAPPER cargo about generate \
    $FAIL_FLAG \
    -c script/licenses/zed-licenses.toml \
    "$TEMPLATE_FILE" >>"$TMP_OUTPUT_FILE"
set +x

sed -i.bak 's/&quot;/"/g' "$TMP_OUTPUT_FILE"
sed -i.bak 's/&#x27;/'\''/g' "$TMP_OUTPUT_FILE" # The ` '\'' ` thing ends the string, appends a single quote, and re-opens the string
sed -i.bak 's/&#x3D;/=/g' "$TMP_OUTPUT_FILE"
sed -i.bak 's/&#x60;/`/g' "$TMP_OUTPUT_FILE"
sed -i.bak 's/&lt;/</g' "$TMP_OUTPUT_FILE"
sed -i.bak 's/&gt;/>/g' "$TMP_OUTPUT_FILE"

rm -rf "${TMP_OUTPUT_FILE}.bak"

if [[ -f "$OUTPUT_FILE" ]] && cmp -s "$TMP_OUTPUT_FILE" "$OUTPUT_FILE"; then
    rm -f "$TMP_OUTPUT_FILE"
else
    mv "$TMP_OUTPUT_FILE" "$OUTPUT_FILE"
fi

echo "generate-licenses completed. See $OUTPUT_FILE"
